# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20', '1.21', '1.22' ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Install dependencies
      run: go mod tidy
      
    - name: Build
      run: go build -v -o spicy_dice ./cmd/main.go  # Build from cmd/main.go

    - name: Test With Go
      run: | 
        go test -json ./... > TestResults-${{ matrix.go-version }}.json
        cat TestResults-${{ matrix.go-version }}.json  
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
